### ISSUE TITLE
support puppet parser validate checking

### ISSUE THREAD

**Issue by divansantana** [benprew/flymake-puppet#3]
Hi,

This flymake-puppet is great!
Would be even better if it also did
`puppet parser validate`
checking.
So one can see within emacs both lint and regular syntax checking.

**Comment by divansantana** [comment]
Nevermind, I'm new to emacs...
Just used flycheck which resolved this.

**Comment by benprew** [comment]
Yeah, sorry, I should update the readme to tell people to just use flycheck.

Thanks!
